import { NextResponse } from "next/server";
import { jobs } from "@/lib/demo-data";
import { buildOfflineBrief } from "@/lib/offline-brief";

export const runtime = "nodejs";

function outputText(payload) {
  if (typeof payload.output_text === "string" && payload.output_text.trim()) return payload.output_text.trim();
  for (const item of payload.output ?? []) {
    for (const part of item.content ?? []) {
      if (typeof part.text === "string" && part.text.trim()) return part.text.trim();
    }
  }
  return "";
}

export async function POST(request) {
  const body = await request.json().catch(() => ({}));
  const job = jobs.find((item) => item.id === body.jobId);
  if (!job) return NextResponse.json({ error: "Unknown synthetic job." }, { status: 400 });

  const apiKey = process.env.OPENAI_API_KEY;
  const model = process.env.OPENAI_MODEL || "gpt-5.6";
  if (!apiKey) {
    return NextResponse.json({
      brief: buildOfflineBrief(job),
      provider: "offline_demo",
      model: "deterministic-rules",
      disclosure: "OPENAI_API_KEY is not configured. This response is deterministic demo content, not model output.",
    });
  }

  const input = {
    candidate: {
      profile: "Synthetic showcase candidate with verified QA, GRC, web, and AI-automation experience.",
      rule: "Never invent employment, education, credentials, skills, or dates.",
    },
    job,
  };
  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      instructions: "You are the decision-brief agent inside a safety-aware job application system. Produce four concise paragraphs: fit verdict, evidence, watch item, and recommendation. Use only supplied facts. Explicitly refuse to fabricate qualifications. Keep the entire response under 140 words.",
      input: JSON.stringify(input),
      max_output_tokens: 350,
    }),
  });
  if (!response.ok) {
    const message = await response.text();
    return NextResponse.json({ error: `OpenAI request failed (${response.status}).`, detail: message.slice(0, 300) }, { status: 502 });
  }
  const payload = await response.json();
  const brief = outputText(payload);
  if (!brief) return NextResponse.json({ error: "The OpenAI response did not contain text." }, { status: 502 });
  return NextResponse.json({
    brief,
    provider: "openai",
    model,
    responseId: payload.id ?? null,
    disclosure: "Generated by OpenAI from synthetic candidate and job data.",
  });
}
